### ISSUE TITLE
five.pt does not escape $ in tal:content

### ISSUE THREAD

**Issue by saily** [zopefoundation/five.pt#1]
- Without `five.pt`: 
  `xml
  <script type="text/javascript" 
          tal:content="string:$$(document).ready(...)" />
  `
  Result:

``` xml
<script type="text/javascript">
$(document).ready(...)
</script>
```
- With `five.pt`: 
  `xml
  <script type="text/javascript" 
          tal:content="string:$$(document).ready(...)" />
  `
  Result (which is wrong):

``` xml
<script type="text/javascript">
$$(document).ready(...)
</script>
```

This disallows me to use `five.pt` as a drop-in replacement.

**Comment by sallner** [comment]
@saily The code of this package got integrated in Zope directly with https://github.com/zopefoundation/Zope/commit/cc059e24c1280bc9eaf077a9adbee1bb4267a7c3, so please open an issue there, if it still persists. Additionally Chameleon is now used as default for template parsing, so this issue should be fixed on the way.
