### ISSUE TITLE
Re-enable Travis for 2.2.x

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/five.pt#12]
I have just created a 2.2.x branch, with the code from before this package was deprecated. It is still in use in Plone 5.0 and 5.1. A colleague has a fix ready, and it would be good to have Travis running before.

I made some changes to the test setup because this was of course broken after being unused for a couple of years. I have one test failure locally, but otherwise it looks good.

**Comment by mauritsvanrees** [comment]
Ah, and the local test failure is this:

    AttributeError: 'NoneType' object has no attribute 'rfind'

And that is exactly what my colleague @fredvd has a fix for. :-)
See also this [thread on community.plone.org](https://community.plone.org/t/cant-save-pfg-mailer-adapter-compilation-failed-exceptions-attributeerror-nonetype-object-has-no-attribute-rfind/5088/3).

**Comment by icemac** [comment]
@mauritsvanrees I re-activated the repos on TravisCI, see https://travis-ci.org/zopefoundation/five.pt.

Please close this issue if this is enough to get the tests running again.

**Comment by mauritsvanrees** [comment]
Thanks. Yes, that is enough.
I have triggered a build of the 2.2.x branch, it is has the single expected failure:
https://travis-ci.org/zopefoundation/five.pt/builds/596636851
