### ISSUE TITLE
ampersands get double encoded with tal:attributes="href ${item/url}"

### ISSUE THREAD

**Issue by datakurre** [zopefoundation/five.pt#2]
Not sure yet, if this is in Chameleon or in five.pt:

```
    <a href="#" tal:attributes="href ${item/url}" />
```

causes ampersands in item/url to be double encoded into `&amp;amp;`

```
    <a href="#" tal:define="url item/url" tal:attributes="href url" />
```

works as expected (results into `&amp;`).

(Need to dig further and try to write failing tests with when more time.)

**Comment by sallner** [comment]
@datakurre This issue seems old enough to be closed. The code of `five.pt` got integrated in Zope directly with https://github.com/zopefoundation/Zope/commit/cc059e24c1280bc9eaf077a9adbee1bb4267a7c3, so a ticket might be opened there if this issue still exists and is relevant.
